### PR TITLE
iOS UI issue fix

### PR DESCRIPTION
**Pull request by sarithapillai8**

### CODE REVIEW

**Review by Linoy339 — APPROVED** [review]
Approved

**Comment by jtorous** [comment]
Can you check this is correct in that it may not be pointing the right version anymore. Right now LAMP is not loading anything for anyone.JohnOn Jan 6, 2023, at 6:35 AM, Linoy339 ***@***.***> wrote:﻿
@Linoy339 approved this pull request.

Approved

**Comment by ZCOEngineer** [comment]
> Can you check this is correct in that it may not be pointing the right version anymore. Right now LAMP is not loading anything for anyone.JohnOn Jan 6, 2023, at 6:35 AM, Linoy339 ***@***.***> wrote:﻿ @Linoy339 approved this pull request. Approved —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

@jtorous we notice that LAMP had a production update yesterday, Lets us check that and see if this is the same tag issue like last time.

**Comment by sarithapillai8** [comment]
@jtorous @ZCOEngineer Production is up now. Again there was 'latest' tag issue.

**Pull request merged**
